### PR TITLE
20 evaluate benefit model

### PR DESCRIPTION
**Pull request by RFOxbury**
---
Just a notebook evaluating the BENEFIT entity from the skills extractor, plus a slightly modified prodigy recipe that I used to label data (the prodigy recipe doesn't need to get merged - just including it here for transparency).

To test the PR, run the notebook `benefits_model_eval.ipynb`.

Please check I've calculated precision, recall and F1 OK.

### CODE REVIEW

**Comment by cmbrennan002** [comment]
Hey! Thanks for this, some really interesting analysis - and the wordcloud is cool to see!

Maybe just because I'm not so familiar with the model (yet), I couldn't tell where the precision/ recall numbers are coming from (although the formulae look fine). Perhaps we can either chat through, or you could add a couple of lines explanation through the doc?

Particularly:
- What does 'other benefit' mean?
- Where does the number '2' come from in the precision calculation?

I wonder if your helper functions (and maybe even the one to create a wordcloud) could be helpful utils for us, as we start exploring the simpler NLP forms - what do you think? Maybe we just refactor those?

I think since this is just EDA, we don't need to tidy it up too much - but perhaps don't need to merge this notebook into dev, either - what do you think?

**Comment by RFOxbury** [comment]
Thanks Clare! You're totally right - the calculations weren't very clear. I've tried to make the notebook a bit clearer.

I've also refactored out the wordclouds function into a script called `eda_utils.py` - if this eventually goes into dev we can use this to collect other functions that might be useful in our EDA.

And yes I don't think the benefits notebook necessarily needs to go into dev. I would like to merge this branch into [explore-jdnw-vr-ssc](https://github.com/nestauk/dap_job_quality/tree/explore-jdnw-vr-ssc) so that the refactored wordcloud function eventually goes into dev. I can delete the notebook before merging? What do you think - is there an easier way to do this?

**Comment by cmbrennan002** [comment]
Hey, I had a look, makes total sense! Interesting that precision is so high, and maybe a hopeful sign for being able to extract a fair bit using a simple method. 

We might have them elsewhere, but I think your tokenize, n-gram, and find_phrase_and_sentence functions are also helpful while we're doing EDA/ simpler extraction, should we add them to the utils file for now? We can always remove them later.

And agree, then we can merge that and delete the notebook! I don't know heaps about github, but sounds sensible to me!

**Comment by RFOxbury** [comment]
> Hey, I had a look, makes total sense! Interesting that precision is so high, and maybe a hopeful sign for being able to extract a fair bit using a simple method.
> 
> We might have them elsewhere, but I think your tokenize, n-gram, and find_phrase_and_sentence functions are also helpful while we're doing EDA/ simpler extraction, should we add them to the utils file for now? We can always remove them later.
> 
> And agree, then we can merge that and delete the notebook! I don't know heaps about github, but sounds sensible to me!

@cmbrennan002 I think I've made these changes now!

**Pull request merged**
